// The plate decal's look: a texture stamped as an emissive deferred decal, generated by CkUsf from
// Shaders/Looks/ImageDecal.ush into Mars content (console: Ck_Usf_GenerateLooks MarsImageDecal). The generator passes
// _Parameters to the shader positionally, so their order IS the .ush signature after In. The plate sets Image per decal
// through a MID; until the master is generated Create_MID_ForLook warns and returns null, and the plate draws no decal.
// Declared here, beside its only consumer: a top-level script asset is visible only in its own file.

asset MarsImageDecal of UCkUsf_LookDefinition
{
    _UshIncludePath       = "/Project/Looks/ImageDecal.ush";
    _UshFunctionName      = n"Mars_Look_ImageDecal";
    _Domain               = ECk_Usf_Domain::Decal;
    _LookName             = n"MarsImageDecal";
    _GeneratedPackageRoot = "/Game/Mars/Materials/GeneratedLooks";

    FCk_Usf_ParamDesc Image;
    Image._Name               = n"Image";
    Image._Type               = ECk_Usf_ParamType::Texture2D;
    Image._DefaultTexturePath = "/Game/Mars/UI/Textures/Backpack_T.Backpack_T";
    _Parameters.Add(Image);

    FCk_Usf_ParamDesc Tint;
    Tint._Name          = n"Tint";
    Tint._Type          = ECk_Usf_ParamType::Vector;
    Tint._DefaultVector = FLinearColor(1.0, 1.0, 1.0, 1.0);
    _Parameters.Add(Tint);

    FCk_Usf_ParamDesc Brightness;
    Brightness._Name          = n"Brightness";
    Brightness._Type          = ECk_Usf_ParamType::Scalar;
    Brightness._DefaultScalar = 1.0f;
    _Parameters.Add(Brightness);

    // Not "Opacity": that name is the generated Custom node's own output.
    FCk_Usf_ParamDesc Coverage;
    Coverage._Name          = n"Coverage";
    Coverage._Type          = ECk_Usf_ParamType::Scalar;
    Coverage._DefaultScalar = 1.0f;
    _Parameters.Add(Coverage);
}

// Placeable pressure plate. The origin is the floor; the slab sinks while at least Occupancy.RequiredCount filtered
// entities stand in the trigger volume, and rises Occupancy.ReleaseDelaySeconds after they leave. Asserts an optional
// MechanismSource while occupied. An optional DecalTexture is stamped on the slab's top face and sinks with it.
class UMars_PressurePlate_EntityScript : UCk_GenericEntityScript_UE
{
    default _ShowInPlaceActors = true;
    default _Replication = ECk_Replication::DoesNotReplicate;

    UPROPERTY(ExposeOnSpawn)
    FTransform SpawnTransform = FTransform::Identity;

    UPROPERTY(ExposeOnSpawn)
    FMars_Trigger_Spec Trigger;
    default Trigger.BoxHalfExtents = FVector(60.0, 60.0, 30.0);
    default Trigger.LocalOffset = FTransform(FRotator::ZeroRotator, FVector(0.0, 0.0, 30.0));
    default Trigger.DetectionFilter = GameplayTag::MakeGameplayTagContainerFromTag(
        GameplayTags::ResolveGameplayTag(n"Probe.Mars.Player"));

    UPROPERTY(ExposeOnSpawn)
    FMars_Occupancy_Spec Occupancy;

    // No source is added while OutputChannel is unset.
    UPROPERTY(ExposeOnSpawn)
    FMars_MechanismSource_Spec Source;

    UPROPERTY(ExposeOnSpawn)
    FVector PlateSize = FVector(120.0, 120.0, 8.0);

    // Drawn with the MarsImageDecal look. Null = no decal.
    UPROPERTY(ExposeOnSpawn)
    TSoftObjectPtr<UTexture2D> DecalTexture;

    // The decal's square, as a fraction of the slab's shorter side.
    private const float64 k_DecalCoverage = 0.8;
    // Half the decal box's depth around the slab's top face.
    private const float64 k_DecalHalfDepth = 4.0;

    UFUNCTION(BlueprintOverride)
    ECk_EntityScript_ConstructionFlow DoConstruct(FCk_Handle& InHandle)
    {
        auto PlateRoot = utils_transform::Add(InHandle, SpawnTransform, ECk_Replication::DoesNotReplicate);
        utils_entity_tag::Add(InHandle, n"TAG_MarsPressurePlate");

        auto PlateNode = utils_scene_node::Create(PlateRoot, FTransform::Identity);
        auto MoverSpec = FMars_Mover_Spec();
        MoverSpec.EndLocation = FVector(0.0, 0.0, -8.0);
        MoverSpec.Duration = 0.25f;
        auto MoverHandle = utils_mover::Add(PlateNode, MoverSpec);

        auto TriggerHandle = utils_trigger::Add(PlateRoot, Trigger);
        utils_occupancy::Add(InHandle, Occupancy, TriggerHandle, MoverHandle);

        if (Source.OutputChannel.IsValid())
        { utils_mechanism_source::Add(InHandle, Source); }

        AddVisuals(PlateRoot, PlateNode);

        return ECk_EntityScript_ConstructionFlow::Finished;
    }

    private void AddVisuals(FCk_Handle_Transform& InRoot, FCk_Handle_SceneNode InPlateNode)
    {
        auto CubeMesh = engine::load::Cube();

        // Engine cube is 100 uu with a centered pivot. The slab rides a child of the plate node so the node's offset
        // stays a pure press translation.
        auto PlateNode = InPlateNode;
        auto PlateTransform = PlateNode.As_Transform();
        AddMesh(PlateTransform, FTransform(FRotator::ZeroRotator, FVector(0.0, 0.0, PlateSize.Z * 0.5), PlateSize * 0.01),
            CubeMesh, assets::load::ProtoGrid_Interactable_Mars_MI(), collision::profile::BlockAll, n"PressurePlate_Slab");

        if (DecalTexture.IsNull() == false)
        { AddDecal(PlateTransform); }

        auto WallMaterial = assets::load::ProtoGrid_Wall_Mars_MI();
        const float64 FrameWidth = 10.0;
        const auto FrameHeight = PlateSize.Z * 0.5;
        const auto SideX = (PlateSize.X + FrameWidth) * 0.5;
        const auto SideY = (PlateSize.Y + FrameWidth) * 0.5;
        const auto AlongXScale = FVector(PlateSize.X + FrameWidth * 2.0, FrameWidth, FrameHeight) * 0.01;
        const auto AlongYScale = FVector(FrameWidth, PlateSize.Y, FrameHeight) * 0.01;

        AddMesh(InRoot, FTransform(FRotator::ZeroRotator, FVector(0.0, -SideY, FrameHeight * 0.5), AlongXScale),
            CubeMesh, WallMaterial, collision::profile::BlockAll, n"PressurePlate_FrameLeft");
        AddMesh(InRoot, FTransform(FRotator::ZeroRotator, FVector(0.0, SideY, FrameHeight * 0.5), AlongXScale),
            CubeMesh, WallMaterial, collision::profile::BlockAll, n"PressurePlate_FrameRight");
        AddMesh(InRoot, FTransform(FRotator::ZeroRotator, FVector(-SideX, 0.0, FrameHeight * 0.5), AlongYScale),
            CubeMesh, WallMaterial, collision::profile::BlockAll, n"PressurePlate_FrameBack");
        AddMesh(InRoot, FTransform(FRotator::ZeroRotator, FVector(SideX, 0.0, FrameHeight * 0.5), AlongYScale),
            CubeMesh, WallMaterial, collision::profile::BlockAll, n"PressurePlate_FrameFront");
    }

    // A decal projects along its local +X, so pitch -90 aims it down at the slab's top face. DecalSize is read-only to
    // script, so the node's scale carries the box size: it multiplies the component's default DecalSize (128, 256, 256
    // half extents). No decal until the MarsImageDecal master is generated (Create_MID_ForLook warns and returns null).
    private void AddDecal(FCk_Handle_Transform& InPlateNode)
    {
        auto Material = utils_usf::Create_MID_ForLook(MarsImageDecal, this);
        if (ck::Is_NOT_Valid(Material))
        { return; }

        auto Texture = System::LoadAsset_Blocking(DecalTexture);
        if (ck::IsValid(Texture))
        { utils_usf::Set_Texture(Material, n"Image", Texture); }

        const auto HalfSize = Math::Min(PlateSize.X, PlateSize.Y) * k_DecalCoverage * 0.5;
        const auto BoxScale = FVector(k_DecalHalfDepth / 128.0, HalfSize / 256.0, HalfSize / 256.0);
        auto Node = utils_scene_node::Create(InPlateNode,
            FTransform(FRotator(-90.0, 0.0, 0.0), FVector(0.0, 0.0, PlateSize.Z), BoxScale));

        auto Archetype = NewObject(this, UDecalComponent);
        Archetype.SetMobility(EComponentMobility::Movable);
        Archetype.SetDecalMaterial(Material);

        auto ComponentParams = utils_unreal_component::Make_Params_FromArchetype(
            Archetype, ECk_UnrealComponent_TickPolicy::DoNotTick, n"PressurePlate_Decal");
        utils_unreal_component::Add(FCk_Handle(Node), ComponentParams);
    }

    // NewObject needs a UObject outer, hence a private method on the entity script.
    private void AddMesh(
        FCk_Handle_Transform& InAttachTo,
        FTransform InLocalTransform,
        UStaticMesh InMesh,
        UMaterialInterface InMaterial,
        FName InCollisionProfile,
        FName InDebugName)
    {
        if (ck::Is_NOT_Valid(InMesh))
        { return; }

        auto Node = utils_scene_node::Create(InAttachTo, InLocalTransform);
        auto NodeEntity = FCk_Handle(Node);

        auto Archetype = NewObject(this, UStaticMeshComponent);
        // Movable: the component receives the entity transform after registration, and the slab moves.
        Archetype.SetMobility(EComponentMobility::Movable);
        Archetype.SetStaticMesh(InMesh);
        if (ck::IsValid(InMaterial))
        { Archetype.SetMaterial(0, InMaterial); }
        Archetype.SetCollisionProfileName(InCollisionProfile);

        auto ComponentParams = utils_unreal_component::Make_Params_FromArchetype(
            Archetype, ECk_UnrealComponent_TickPolicy::DoNotTick, InDebugName);
        utils_unreal_component::Add(NodeEntity, ComponentParams);
    }
}
