"""Bakes MeatSlab_Mars_SM's triangles into Script/Generated/Mars_MeatSlabMesh.as, the table the cutting station builds and
slices its procedural meat from (the AngelScript binder exposes none of UKismetProceduralMeshLibrary, so the station cannot
read a static mesh's sections at runtime). Run headless after the meats builder:

    blender -b --factory-startup --python D:\Repo\Mars\Tools\Blender\mars_cooking\export_meatslab_table.py

Unreal local cm (Blender y mirrored), unique vertices, triangle index triples, and each triangle's section (0 Flesh, 1 fat
cap). Normals are not baked: the station shades every triangle flat from its own corners.
"""
import os
import sys

import bpy

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import food_spec as spec  # noqa: E402

FBX = os.path.join(spec.EXPORT_DIR, "MeatSlab_Mars_SM.fbx")
OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(HERE))), "Script", "Generated", "Mars_MeatSlabMesh.as")


def main():
    for o in list(bpy.data.objects):
        bpy.data.objects.remove(o, do_unlink=True)
    bpy.ops.import_scene.fbx(filepath=FBX)
    obj = next(o for o in bpy.data.objects if o.type == "MESH")
    mesh = obj.data
    mesh.calc_loop_triangles()
    verts = [(v.co.x * 100.0, -v.co.y * 100.0, v.co.z * 100.0) for v in mesh.vertices]
    tris, sections = [], []
    for t in mesh.loop_triangles:
        a, b, c = t.vertices
        tris.append((a, c, b))                      # the Y mirror flips the winding; flip it back so faces point outward
        sections.append(mesh.polygons[t.polygon_index].material_index)
    slots = [m.name if m else "" for m in mesh.materials]
    lo = [min(v[i] for v in verts) for i in range(3)]
    hi = [max(v[i] for v in verts) for i in range(3)]
    lines = [
        "// GENERATED by Tools/Blender/mars_cooking/export_meatslab_table.py from MeatSlab_Mars_SM.fbx - do not edit.",
        "// %d vertices, %d triangles, sections %s; Unreal local cm, pivot at the base centre, long axis +X; bounds %s .. %s."
        % (len(verts), len(tris), slots, [round(x, 2) for x in lo], [round(x, 2) for x in hi]),
        "namespace mars_meatslab_mesh",
        "{",
        "    const int k_VertexCount = %d;" % len(verts),
        "    const int k_TriangleCount = %d;" % len(tris),
        "    const int k_SectionCount = %d;" % len(slots),
        "    const FVector k_BoundsMin = FVector(%.3f, %.3f, %.3f);" % tuple(lo),
        "    const FVector k_BoundsMax = FVector(%.3f, %.3f, %.3f);" % tuple(hi),
        "",
        "    TArray<FVector> Make_Vertices()",
        "    {",
        "        TArray<FVector> V;",
        "        V.Reserve(k_VertexCount);",
    ]
    for x, y, z in verts:
        lines.append("        V.Add(FVector(%.3f, %.3f, %.3f));" % (x, y, z))
    lines += ["        return V;", "    }", "", "    TArray<int> Make_Triangles()", "    {", "        TArray<int> T;",
              "        T.Reserve(k_TriangleCount * 3);"]
    for i in range(0, len(tris), 8):
        chunk = tris[i:i + 8]
        lines.append("        " + " ".join("T.Add(%d); T.Add(%d); T.Add(%d);" % t for t in chunk))
    lines += ["        return T;", "    }", "", "    // The section (material slot) of each triangle: 0 = Flesh, 1 = the fat cap (Skin).",
              "    TArray<int> Make_Sections()", "    {", "        TArray<int> S;", "        S.Reserve(k_TriangleCount);"]
    for i in range(0, len(sections), 32):
        lines.append("        " + " ".join("S.Add(%d);" % s for s in sections[i:i + 32]))
    lines += ["        return S;", "    }", "}", ""]
    with open(OUT, "w", newline="\n") as fh:
        fh.write("\n".join(lines))
    print("MEATSLAB_TABLE_OK %s verts %d tris %d sections %s" % (OUT, len(verts), len(tris), slots))


main()
